### DISCUSSION TITLE
Azure IPAM on AKS

### DISCUSSION THREAD

**Discussion by DCMattyG** [Azure/ipam#32] [Ideas]
Hello @hmizael, I wanted to dive deeper into this ask with you here...

For IPAM running on AKS, I have a few design questions for you:

1. Would you like to see an option to deploy IPAM on a new AKS cluster, or it's more likely users will have an existing one they want to deploy to?
2. What is the desired way to handle ingress? Would you put an App Gateway in front, or just use the native k8s ingress?
3. If k8s ingress, how would you do path-based routing to map "/" to the UI and "/api" to the engine? NGINX? Traefik? HA Proxy? Other?
4. How would you handle SSL certs? App Service and Azure Container apps have this functionality built-in...how would/should users handle this with AKS?
5. How would you handle DNS so that the FQDN for IPAM running on AKS is resolved properly for users?

I definitely have ideas on how I would handle these items, but I'm more interested in your thoughts on how this should be automated in such a way many users could benefit from this solution, as opposed to just providing design guidance around how to deploy IPAM on AKS.

Thanks so much!

**Comment by hmizael** [comment]
Thank you so Much for your attention @DCMattyG!

So I'll answer based on what I did to deploy in my environment, an already existing production AKS:

I created a Cosmos DB account like Bicep would;
I didn't create other resources like Kv, App Services etc.

I created a Private Endpoint for Cosmos, to bring a little more security and traffic control;
As accessing IPAM only by private link, we do not use any External Ingress or Application Gateway solution;
We do not use the NGinx Container, as we already use an NGinx as an Ingress-Controller, so we use the existing one.

After this briefing, let's go to the settings for the items you mentioned:

I'm then handling the input with nginx ingress:

_ingress-ipam.yaml_:
```
apiVersion: networking.k8s.io/v1
type: input
metadata:
  name: ipam
  namespace: ipam
  notes:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: <CERT MANAGER NAME>
specification:
  tls:
  - hosts:
      - <DNS NAME>
    secretName: ipam-tls
  the rules:
  - host: <DNS NAME>
    http:
      ways:
        - way: /
          pathType: prefix
          Internal process:
            service:
              name: ipam-ui
              door:
                number: 80
        - path: /api
          pathType: prefix
          Internal process:
            service:
              name: motor-ipam
              door:
                number: 80
```

As you can see, I'm using port mapping by ingress.
For the certificate issue, as we have the Cert-Manager already configured in the cluster, just point it out and we also have the certificate released.

For DNS, I created a record in our Private DNS Zone to point to Ingress.

Enjoy then and I bring my Deploy, Service, Secrets settings etc.
Note: in relation to the secret, we use the External Secrets Operators here, which brings the Kv secrets to the Cluster (https://external-secrets.io/)

_deployment-ipam-engine.yaml_:
```
apiVersion: apps/v1
type: deployment
metadata:
  name: motor-ipam
  namespace: ipam
  labels:
    app: ipam
    service: engine
specification:
  replicas: 1
  selector:
    matchLabels:
      app: ipam
      service: engine
  model:
    metadata:
      labels:
        app: ipam
        service: engine
    specification:
      containers:
      - name: motor-ipam
        image: azureipam.azurecr.io/ipam-engine:latest
        Resources: {}
        envDe:
        - secretRef:
            name: ipam
```

_deployment-ipam-ui.yaml_:
```
apiVersion: apps/v1
type: deployment
metadata:
  name: ipam-ui
  namespace: ipam
  labels:
    app: ipam
    service: ui
specification:
  replicas: 1
  selector:
    matchLabels:
      app: ipam
      service: ui
  model:
    metadata:
      labels:
        app: ipam
        service: ui
    specification:
      containers:
      - name: ipam-ui
        image: azureipam.azurecr.io/ipam-ui:latest
        Resources: {}
        envDe:
        - secretRef:
            name: ipam
```

_service-ipam-engine.yaml_:
```
apiVersion: v1
type: service
metadata:
  name: motor-ipam
  namespace: ipam
  labels:
    app: ipam
    service: engine-ui
specification:
  selector:
    app: ipam
    service: engine
  doors:
    - name: http
      port: 80
      targetPort: 80
```

_service-ipam-ui.yaml_:
```
apiVersion: v1
type: service
metadata:
  name: ipam-ui
  namespace: ipam
  labels:
    app: ipam
    service: service-ui
specification:
  selector:
    app: ipam
    service: ui
  doors:
    - name: http
      port: 80
      targetPort: 80
```

Then that's it! Remembering that this form of deployment is what works for me, but I think native support for AKS by the more comprehensive Azure IPAM would be very valid, allowing you to choose between Application Gateway or Ingress-Controller, direct support for Kv and so on...

Thanks again for your attention!
