### ISSUE TITLE
'latest' tag is missing from azureipam.azurecr.io/ipamdev-ui

### ISSUE THREAD

**Issue by WilliamDahlen** [Azure/ipam#345]
**Describe the bug**
When using the latest tag for the azureipam.azurecr.io/ipamdev-ui, it fails to pull.

`2025-02-11T11:48:59.703Z ERROR - DockerApiException: Docker API responded with status code=NotFound, response={"message":"manifest for azureipam.azurecr.io/ipamdev-ui:latest not found: manifest unknown: manifest tagged by \"latest\" is not found"}`

**To Reproduce**
Set your config to
```
version: '3.8'
services:
  ipam-ui:
    environment:
      REACT_APP_AZURE_ENV: ${AZURE_ENV}
      REACT_APP_UI_ID: ${UI_APP_ID}
      REACT_APP_ENGINE_ID: ${ENGINE_APP_ID}
      REACT_APP_TENANT_ID: ${TENANT_ID}
    image: azureipam.azurecr.io/ipamdev-ui:latest
  ipam-engine:
    environment:
      AZURE_ENV: ${AZURE_ENV}
      CLIENT_ID: ${ENGINE_APP_ID}
      CLIENT_SECRET: ${ENGINE_APP_SECRET}
      TENANT_ID: ${TENANT_ID}
      COSMOS_URL: ${COSMOS_URL}
      COSMOS_KEY: ${COSMOS_KEY}
      KEYVAULT_URL: ${KEYVAULT_URL}
    image: azureipam.azurecr.io/ipamdev-engine:latest
  nginx-proxy:
    image: azureipam.azurecr.io/ipamdev-lb:latest
    ports:
      - "80:8080"
```

**Expected behavior**
The latest tag should be available looking at the workflow files in this repo. Is there a cleanup gone wrong maybe?
